 # START-MUGUR-REGION

 FORCE_NKRO       = yes
     LEADER_ENABLE    = no
     RGBLIGHT_ENABLE  = yes
     TAP_DANCE_ENABLE = no
     COMBO_ENABLE     = no
     CAPS_WORD_ENABLE = no 

# END-MUGUR-REGION 