// START-MUGUR-REGION
// END-MUGUR-REGION

#define EE_HANDS
#define TAPPING_TERM 175
#define COMBO_TERM 300
#define RETRO_TAPPING
#define UNICODE_SELECTED_MODES UC_LNX, UC_MAC
#define VENDOR_ID  0x4653
#define PRODUCT_ID 0x0001
